---
- name: Ensure logrotate is installed
  package:
    name: logrotate
    state: present
  become: true

- name: Ensure the directory for rotated log files exist
  file:
    path: "{{ logs_dir }}/{{ old_dir }}"
    state: directory
  become: true

- name: Deploy the configuration for apache
  template:
    src: logrotate_httpd.j2
    dest: /etc/logrotate.d/httpd
  become: true